version: '3'
services:
  web:
    build: .
    environment:
      PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
      VIEW: ${VIEW}
      GULPFILE: nyu-gulpfile.js
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - ./primo-explore:/app/primo-explore
      - ./packages:/app/packages
