version: '3'
services:
  web:
    build: .
    environment:
      PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
      # VIEW: BHS-NUI
      # VIEW: CU-NUI
      # VIEW: NYHS-NUI
      # VIEW: NYSID-NUI
      VIEW: NYU-NUI
      # VIEW: NYUAD-NUI
      # VIEW: NYUSH-NUI
      # VIEW: CENTRAL_PACKAGE
      GULPFILE: nyu-gulpfile.js
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
