version: '3'
services:
  web:
    build:
      context: .
    image: primo-explore-devenv
    environment:
      PROXY_SERVER: http://bobcatdev.library.nyu.edu:80
      VIEW:
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - ./primo-explore:/app/primo-explore
      - ./packages:/app/packages